### ISSUE TITLE
Image Generation Testing Mode

### ISSUE THREAD

**Issue by vikktrey123** [JartanFTW/Trade-Notifier#30]
add a testing mode, just sends the webhook with a fake trade or your most recent trade. useful for theme creators.

**Comment by JartanFTW** [comment]
Two ways that I can think of that would be effective to do this:
1. On startup just removes one out of 10 of the saved confirmed trades, resulting in immediately detecting that 'one' as a new trade, sending a single notification, and then continuing on as normal.
2. As above, but instead of only removing it once, removes it every X amount of time till testing mode is disabled and Horizon is restarted.
I would like to hear others thoughts on this.

**Comment by nwho99** [comment]
Both options suffice, I prefer Option 1, but that's just personal preference.
